# Aula 02 - Python

## Dados Numéricos

In [10]:
# Variável inteira (Resultou em INT, ou seja, inteiro: significa que o número é um inteiro)
a = 1
print('Valor de a = '+str(a))
type(a)
# OBS: STR converte A em string, ou seja, em um caracter letra/número; TYPE  mostra a variável na tela;

Valor de a = 1


int

In [18]:
# Variável dupla precisão (Resultou em um FLOAT: número com vírgula.)
b = 1.0
print(b)
type(b)

1.0


float

In [19]:
# Converter float para int (Arredonda: do número com vírgula para número inteiro)
c = int (b)
print (c)
type (c)
# OBS: Na linha 11 tinha dito que b valia 1.0. Nesta linha 12, digo que c vale um b inteiro. Logo, c é igual ao b arredondado.

1


int

In [24]:
# Declarando NaN (NaN significa Not a Number. É um valor especial usado para representar resultados inválidos ou indefinidos em operações matemáticas)
import numpy as np
d = np.nan
print(d)
type(d)
# Disse aqui que d é igual a um número ainda desconhecido, um dado ausente. Isso permite que seja representado um "valor" na serie de dados.

nan


float

In [25]:
# Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)
# As operações aqui com d* ou d+ resultam em nan pois d é um NaN multiplicado/somado com qualquer outro sempre irá resultar em nan
# Já quando faz np.nansum, é uma função utilizada para calcular a soma de valores em uma matriz ignorando os valores nan. Logo, e calculou a soma dos valores d+1, sendo que nan foi ignorado (=0).

nan
nan
1.0


## Dados de Texto

In [30]:
# Declaração de variável texto
f = 'Fábio'
g = "Gabriel"
print(f)
print(g)
print(f+g)
print (f+' '+g)
#Notar que para escrever um texto pode usar ' ou "; Para somar e dar espaço entre os caracteres, +' '+ 

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


## Dados tipo BOOL - lógica

In [34]:
a == 1
# Já tinha atribuído o valor de a no início do código. == é utilizado para verificar se dois valores são iguais. Se sim: True; Se não, False.

True

In [36]:
h = (a==1)
print(h)
type(h)
# Atribui à variável h o resultado da comparação a == 1. Como anteriormente tinha dado True, então agora a variável h irá conter o valor booleano True.

True


bool

In [39]:
h = (a==2)
print(h)
type(h)
# Fez o mesmo que o anterior, porém como agora a =/ 1, então h resulta como False

False


bool

In [40]:
i = True
type(i)
#i resultou em BOOL pois True e False são tipo bool

bool

In [41]:
ii = 'True'
type(ii)
# Resulta em string pois está entre '', logo vira um texto e não um bool

str

## Operação de comparação
### Considerando os valores anteriormente atribuídos às variáveis

In [42]:
# Operação == (IGUAL)
a == b

True

In [43]:
# Operação >< (MAIOR ou MENOR)
a>b

False

In [44]:
# Operação != (DIFERENTE: Retorna True se realmente forem diferentes)
a!=b
# Como a = b, resultou False

False

In [46]:
# Operação >= ou <=
a>= b
# Nesse caso, a e b são iguais

True

## Operações Matemáticas

In [47]:
# Soma
a+b

2.0

In [48]:
# Soma e atribui valor
ab = a+b
print (ab)

2.0


In [51]:
# Multiplicação
l = a*b # não usar mais l como variável!
print ("Não use l como nome de variável") #l é =1, porém pedi para print outra coisa
j = a*b
print(j)

Não use l como nome de variável
1.0


In [52]:
# Divisão
a/b

1.0

In [53]:
# Potência
5**2

25

In [54]:
# Operações matemáticas com a biblioteca MATH
import math
math.exp(10)

22026.465794806718

In [55]:
math.exp(0)

1.0

In [56]:
math.exp(a)

2.718281828459045

In [57]:
math.exp(-10)

4.5399929762484854e-05

In [58]:
import math as mt #importou o módulo math e renomeou como mt
mt.log(c)

0.0

In [59]:
mt.log10(100)

2.0

## Listas

In [61]:
myFirstList = [1, 2, 3] #cria uma lista, ou seja, uma estrutura de dados que armazena os itens de forma ordenada
print(myFirstList)

[1, 2, 3]


In [62]:
# Acessando valores da lista pelo index
print(myFirstList[0]) #puxa o primeiro número da lista
print(myFirstList[2]) #puxa o terceiro número da lista

1
3


In [66]:
myFirstList == a #False pois a lista não é igual a 1, valor da variável a

False

In [65]:
myFirstList[0] == a #True pois o item zero é igual a variável a

True

In [67]:
mySecList = [1, a, 'c']
print(mySecList)

[1, 1, 'c']


In [69]:
type(mySecList) #o tipo da variável é uma lista

list

In [72]:
type(mySecList[2]) #como o terceiro item da lista é um texto, o tipo é string

str

In [73]:
type(mySecList[1]) #como a tem valor =1 inteiro, o tipo é inteiro

int

## Caminhos = PATH

In [79]:
path = r"C:\Users\Acer\Desktop\ENS5173_Barbara\ENS5173_Barbara"
print(path)
#Defini o caminho do arquivo usando r antes, significa que os caracteres de escape dentro da string não são interpretaods.

C:\Users\Acer\Desktop\ENS5173_Barbara\ENS5173_Barbara


In [80]:
path = "C:/Users/Acer/Desktop/ENS5173_Barbara/ENS5173_Barbara"
print(path)
#VERIFICAR COM PROF QUAL O OBJETIVO DESTA LINHA

C:/Users/Acer/Desktop/ENS5173_Barbara/ENS5173_Barbara


In [81]:
import os #Listar arquivos na pasta
os.listdir(path)

['.git',
 '.gitignore',
 '.ipynb_checkpoints',
 'Aula01.ipynb',
 'inputs',
 'README.md',
 'scripts',
 'venv']

In [82]:
# Selecionar o primeiro arquivo listado
os.listdir(path)[0]

'.git'

In [84]:
#Concatenando caminhos
path+"/"+os.listdir(path)[0]

'C:/Users/Acer/Desktop/ENS5173_Barbara/ENS5173_Barbara/.git'

In [85]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0])

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'packed-refs',
 'refs']

In [86]:
# Diretório que estou trabalhando
os.getcwd()

'C:\\Users\\Acer\\Desktop\\ENS5173_Barbara\\ENS5173_Barbara\\venv\\Scripts'

In [88]:
# Mudo de diretório para o caminho
os.chdir('C:\\Users\\Acer\\Desktop\\ENS5173_Barbara\\')

In [89]:
os.getcwd()

'C:\\Users\\Acer\\Desktop\\ENS5173_Barbara'

In [90]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

Criando diretório C:\Users\Acer\Desktop\ENS5173_Barbara/test


In [91]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

Criando diretório C:\Users\Acer\Desktop\ENS5173_Barbara/test2


In [92]:
#NESTA ETAPA DE PATH: Mexemos no diretório do computador, alterando caminhos e pastas

## Numpy Arrays e Pandas DataFrames

In [93]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)

numpy.ndarray

In [94]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)

[ 1  2  3 10 20 55]


In [95]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10)
print(n)
# Dimensões da matrix
print(n.shape)

[[6.63161855e-01 4.96248062e-01 7.86116520e-01 9.40247893e-01
  7.71043981e-01 6.85724573e-01 2.09341708e-01 1.84273469e-01
  9.64085376e-01 3.59774828e-01]
 [7.21637248e-01 5.57872361e-01 2.91516361e-01 4.72858588e-01
  2.10489196e-01 4.89985875e-01 5.22369511e-01 8.89652822e-01
  9.03972089e-02 2.60436363e-01]
 [9.86350387e-01 7.76598251e-01 3.28662605e-01 1.83332853e-01
  1.93828944e-01 2.03569250e-01 6.01241149e-01 1.53912211e-01
  5.70124836e-01 6.93103236e-01]
 [4.53493120e-01 2.61835106e-01 6.80776292e-01 1.82199236e-01
  7.69070659e-01 9.52958630e-01 2.43508518e-01 4.41914935e-01
  5.59543599e-06 4.72632781e-01]
 [1.18780951e-01 2.34469606e-02 7.69253797e-01 8.31058023e-01
  8.09965328e-01 8.28949851e-01 6.28497615e-01 9.55497863e-01
  5.12067895e-01 7.59092936e-01]
 [2.99127823e-02 8.70999594e-01 9.83462473e-01 9.03290358e-02
  9.80630553e-01 4.10881096e-01 3.72389191e-01 7.31421474e-02
  6.12707821e-01 8.98954900e-01]
 [7.48050047e-01 2.23254914e-01 6.62289872e-01 1.57017410e

In [101]:
# Acessando valores da matriz
# : depois da vírgula significa que todas as colunas devem ser retornadas
n[0,:] # Acessa a primeira linha da matriz, do primeiro ao último item

array([0.66316185, 0.49624806, 0.78611652, 0.94024789, 0.77104398,
       0.68572457, 0.20934171, 0.18427347, 0.96408538, 0.35977483])

In [102]:
n[:,0] # Acessa uma coluna específica, neste caso a primeira
# : antes da vírgula significa que todas as linhas devem ser retornadas

array([0.66316185, 0.72163725, 0.98635039, 0.45349312, 0.11878095,
       0.02991278, 0.74805005, 0.23829404, 0.33590908, 0.67293757])

In [103]:
n[:,1:5] # usado para acessar um intervalo de colunas na matriz, sendo que : antes da vírgula indica todas as linhas e 1:5 indica acesso as colunas do índice 1 até o 5 inclusive

array([[0.49624806, 0.78611652, 0.94024789, 0.77104398],
       [0.55787236, 0.29151636, 0.47285859, 0.2104892 ],
       [0.77659825, 0.32866261, 0.18333285, 0.19382894],
       [0.26183511, 0.68077629, 0.18219924, 0.76907066],
       [0.02344696, 0.7692538 , 0.83105802, 0.80996533],
       [0.87099959, 0.98346247, 0.09032904, 0.98063055],
       [0.22325491, 0.66228987, 0.15701741, 0.64850273],
       [0.95069285, 0.82462829, 0.44076096, 0.87192905],
       [0.84176474, 0.21112908, 0.17600113, 0.80328724],
       [0.07332396, 0.99617584, 0.58456339, 0.18182203]])

In [104]:
n[0,1:5] # acessa a primeira linha (0) e o intervalo de colunas de 1 ate 5

array([0.49624806, 0.78611652, 0.94024789, 0.77104398])

In [107]:
n[0, -1] #acessa o último elemento da primeira linha

0.3597748284439304

In [108]:
n[0,4:-1]

array([0.77104398, 0.68572457, 0.20934171, 0.18427347, 0.96408538])

In [109]:
n[0,4:]

array([0.77104398, 0.68572457, 0.20934171, 0.18427347, 0.96408538,
       0.35977483])

In [111]:
an = np.log(n*5) #calcula o logatirmode cada elemento da matriz por 5
print(an)

[[  1.19870172   0.90875856   1.36878766   1.54782619   1.34942805
    1.23215868   0.04565052  -0.08189647   1.57286249   0.58716099]
 [  1.28320522   1.02581283   0.37677877   0.86047901   0.05111696
    0.8960592    0.96005785   1.49251393  -0.79410397   0.26404118]
 [  1.59569429   1.3566058    0.49671434  -0.087014    -0.03134133
    0.01768888   1.10067873  -0.26193499   1.04753798   1.24286159]
 [  0.81866273   0.26939757   1.22491639  -0.09321658   1.34686548
    1.56125413   0.19683456   0.79280004 -10.48412138   0.86000136]
 [ -0.52103632  -2.14357649   1.34710358   1.42438225   1.39867407
    1.42184229   1.14501487   1.56391516   0.94013986   1.33380685]
 [ -1.90003148   1.47132414   1.59276211  -0.79485841   1.58987842
    0.7199865    0.62162215  -1.00591259   1.11957082   1.5029155 ]
 [  1.31915252   0.10999686   1.19738597  -0.24196068   1.17634885
    0.77084391  -0.79421195   1.32489417   0.07325525   0.49628954]
 [  0.17518799   1.55887367   1.41661537   0.79018532  